#!/usr/bin/env bash
docker run -d --rm -p 8888:8888 -v $(pwd):/work -v ~/.ssh:/home/jovyan/.ssh -v ~/.gitconfig:/etc/gitconfig --name advent-of-code-2019  advent-of-code:latest jupyter lab --notebook-dir=/work --LabApp.token=''
sleep 2
open http://localhost:8888
docker attach advent-of-code-2019
