#!/usr/bin/env bash
docker pull docker.pkg.github.com/cqkh42/advent-of-code-2019/advent-of-code-2019:latest
docker run -d --rm -p 8888:8888 -v $(pwd):/work -v ~/.ssh:/home/jovyan/.ssh -v ~/.gitconfig:/etc/gitconfig --name advent-of-code-2019 docker.pkg.github.com/cqkh42/advent-of-code-2019/advent-of-code-2019:latest
sleep 2
open http://localhost:8888
docker attach advent-of-code-2019
